visible = 0
commands =
@"
[TXT:Skip intro?]
[CHO:0002:0001]
[LBL:0001]
[TXT:Hello there! It's so nice to meet you!]
[TXT:Welcome to the WORLD OF PHONES!]
[SND:0001:bgm_intro]
[FOI]
[FAI]
[TXT:My name is Professor Rocky, and I'm the authority on phones worldwide.]
[TXT:Big phones, small phones, smart phones, dumb phones...]
[TXT:As a preservationist, it's my duty to preserve them all.]
[TXT:And as time and technology advance, the technology of the past is just left to rot.]
[TXT:Even though today some old technology keeps getting used, our old phones are forgotten.]
[TXT:These phones are more than just phones -- they're valuable steps that led us to where we are today.]
[TXT:The preservation of them are extremely important, and that's what I do.]
[TXT:That's enough about me. What about you?]
[LBL:0004]
[TXT:What do you look like?]
[TXT:(Insert appearance window here)]
[TXT:You look like this?]
[CHO:0003:0004]
[LBL:0003]
[TXT:I see. And what's your name?]
[TXT:(Insert naming window here)]
[TXT:That's your name?]
[CHO:0005:0003]
[LBL:0005]
[TXT:Nice to meet you! Welcome to the team.]
[TXT:Are you ready to embark on a quest of epic proportions?]
[TXT:I've given you $500 to start off with.]
[TXT:Have fun out there! And be sure to drop by my lab later.]
[LBL:0002]
[FAO]
[WAI:0030]
[GTR:0248:0152:rm_test]
[FAI]
"